import { ImageResponse } from 'next/og';

export const OG_SIZE = { width: 1200, height: 630 } as const;
export const OG_CONTENT_TYPE = 'image/png';

export interface OgCardProps {
  title: string;
  subtitle?: string;
  tags?: string[];
  footer: string;
  /** Small label above the title, e.g. "Project". */
  kicker?: string;
}

/**
 * The share card, rendered by Satori through next/og.
 *
 * Replaces the hand-made public/og-image.png (ADR-025): that file said the
 * same thing for every URL, and had to be regenerated by hand whenever the
 * headline changed. This is drawn from the same rows the page reads, so a
 * project page unfurls with its own title and stack.
 *
 * Satori supports a subset of CSS: flexbox only (every element with more
 * than one child needs `display: flex`), no CSS variables, no grid.
 */
export function ogCard({ title, subtitle, tags = [], footer, kicker }: OgCardProps): ImageResponse {
  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          padding: '64px 72px',
          backgroundColor: '#0a0a0f',
          backgroundImage:
            'radial-gradient(circle at 15% 20%, rgba(99,102,241,0.28) 0%, rgba(99,102,241,0) 45%), radial-gradient(circle at 85% 90%, rgba(139,92,246,0.22) 0%, rgba(139,92,246,0) 45%)',
          color: '#e4e4ef',
          fontFamily: 'sans-serif',
        }}
      >
        <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
          {kicker && (
            <div
              style={{
                display: 'flex',
                fontSize: 22,
                letterSpacing: 4,
                textTransform: 'uppercase',
                color: '#818cf8',
                fontWeight: 600,
              }}
            >
              {kicker}
            </div>
          )}
          <div
            style={{
              display: 'flex',
              fontSize: title.length > 40 ? 60 : 76,
              fontWeight: 800,
              lineHeight: 1.1,
              letterSpacing: -2,
              maxWidth: 1000,
            }}
          >
            {title}
          </div>
          {subtitle && (
            <div style={{ display: 'flex', fontSize: 30, color: '#9898b0', lineHeight: 1.35, maxWidth: 980 }}>
              {subtitle}
            </div>
          )}
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 26 }}>
          {tags.length > 0 && (
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 12 }}>
              {tags.slice(0, 6).map((t) => (
                <div
                  key={t}
                  style={{
                    display: 'flex',
                    padding: '8px 18px',
                    borderRadius: 999,
                    backgroundColor: 'rgba(255,255,255,0.06)',
                    border: '1px solid rgba(255,255,255,0.12)',
                    fontSize: 22,
                    color: '#c7c7d6',
                  }}
                >
                  {t}
                </div>
              ))}
            </div>
          )}
          <div style={{ display: 'flex', alignItems: 'center', gap: 16, fontSize: 24, color: '#82829c' }}>
            <div
              style={{
                display: 'flex',
                width: 40,
                height: 40,
                borderRadius: 10,
                backgroundColor: '#6366f1',
                color: '#fff',
                alignItems: 'center',
                justifyContent: 'center',
                fontWeight: 700,
                fontSize: 22,
              }}
            >
              K
            </div>
            {footer}
          </div>
        </div>
      </div>
    ),
    { ...OG_SIZE },
  );
}
