#!/usr/bin/env node
/**
 * Snapshot the live database schema into a fixture the test suite checks
 * queries against.
 *
 * Three separate production bugs in this project were the same defect: code
 * referencing a table or column that does not exist, failing silently at
 * runtime because the error was swallowed or the value was merely undefined.
 *
 *   fetchResumeUrl()      -> table  `resume_versions`   (never existed)
 *   fetchProjectMetrics() -> table  `project_metrics`   (never existed)
 *   Resume.jsx / About.jsx -> nine `profiles` columns   (never existed)
 *
 * `supabase gen types typescript` is the real answer and needs CLI auth. This
 * is the version that works with the anon key alone: snapshot what exists,
 * commit it, and let a test fail when the code drifts from it.
 *
 * Usage:  node scripts/introspect-schema.mjs
 * Reads VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY from the environment
 * or from .env.
 */

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT = path.join(ROOT, 'src', '__tests__', 'fixtures', 'schema.json');

function loadEnv() {
  const env = { ...process.env };
  const envPath = path.join(ROOT, '.env');
  if (fs.existsSync(envPath)) {
    for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (m && !env[m[1]]) env[m[1]] = m[2].replace(/^["']|["']$/g, '').trim();
    }
  }
  return env;
}

// Every relation the application reads. Kept explicit so a table dropped from
// the code is noticed here rather than silently disappearing from the snapshot.
const RELATIONS = [
  'profiles', 'projects', 'project_sections', 'project_storytelling',
  'external_profiles', 'skills', 'experience', 'achievements',
  'contact_messages', 'analytics', 'analytics_daily_visits',
  'resume', 'site_content', 'activity_logs', 'feature_flags',
];

const env = loadEnv();
const URL_BASE = env.VITE_SUPABASE_URL;
const KEY = env.VITE_SUPABASE_ANON_KEY;

if (!URL_BASE || !KEY) {
  console.error('Missing VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY');
  process.exit(1);
}

const headers = { apikey: KEY, Authorization: `Bearer ${KEY}` };

const snapshot = {
  generatedAt: new Date().toISOString(),
  note: 'Generated by scripts/introspect-schema.mjs. Re-run after any schema change.',
  relations: {},
};

for (const rel of RELATIONS) {
  const res = await fetch(`${URL_BASE}/rest/v1/${rel}?select=*&limit=1`, { headers });

  if (res.status === 404) {
    snapshot.relations[rel] = { exists: false, columns: null };
    console.log(`  ${rel.padEnd(24)} MISSING`);
    continue;
  }

  if (!res.ok) {
    snapshot.relations[rel] = { exists: true, columns: null, note: `probe returned ${res.status}` };
    console.log(`  ${rel.padEnd(24)} exists (columns unknown, HTTP ${res.status})`);
    continue;
  }

  const rows = await res.json();

  if (!Array.isArray(rows) || rows.length === 0) {
    // Readable but empty, or every row hidden by RLS. Columns cannot be
    // derived from data; recorded as unknown so the test skips column checks
    // rather than asserting against an empty list.
    snapshot.relations[rel] = { exists: true, columns: null, note: 'no readable rows' };
    console.log(`  ${rel.padEnd(24)} exists (no readable rows)`);
    continue;
  }

  const columns = Object.keys(rows[0]).sort();
  snapshot.relations[rel] = { exists: true, columns };
  console.log(`  ${rel.padEnd(24)} ${columns.length} columns`);
}

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, JSON.stringify(snapshot, null, 2) + '\n', 'utf8');
console.log(`\nWrote ${path.relative(ROOT, OUT)}`);
